steps:
  - name: 'maven:3.8.5-eclipse-temurin-17-alpine'
    args:
      - clean
    entrypoint: mvn

  - name: 'maven:3.8.3-eclipse-temurin-11'
    args:
      - package
      - '-U'
    entrypoint: mvn
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/mambamhs/github_lizilong1123_test:latest'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_IMAGE_NAME:$COMMIT_SHA']
    id: Push
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - '--namespace=test'
      - 'deployment/test'
      - 'github-lizilong1123-test-sha256-1=$_IMAGE_NAME:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_K8S_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_K8S_CLUSTER}'
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
substitutions:
  _K8S_APP_NAME: test
  _IMAGE_NAME: gcr.io/mambamhs/github_lizilong1123_test
  _K8S_CLUSTER: mamba-cluster
  _K8S_COMPUTE_ZONE: us-central1
  _DOCKERFILE_NAME: Dockerfile
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
